### ISSUE TITLE
npx gqlPrune - 404 not found

### ISSUE THREAD

**Issue by binary64** [Krister-Johansson/gqlPrune#2]
Hi as per readme, I am trying to run `npx gqlPrune` but I get this error
```
$ npx gqlPrune
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/gqlPrune - Not found
npm ERR! 404
npm ERR! 404  'gqlPrune@*' is not in this registry.
npm ERR! 404 This package name is not valid, because
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

```

**Comment by Krister-Johansson** [comment]
For some reason the builder did not include the dist folder... Wokring on it <3

**Comment by binary64** [comment]
Just noticed the inner error: `1. name can no longer contain capital letters`
`npx gqlprune` seems to be installing..

**Comment by Krister-Johansson** [comment]
I tried to publish a new build but i still get the same resutl...
https://www.npmjs.com/package/gqlprune?activeTab=code

Did the package generate the `gqlPrune.config.yaml` file?

I will try tomorrow and see how the new package works in my project again

**Comment by bilal54498** [comment]
@Krister-Johansson package didn't generate the `gqlPrune.config.yaml` as it didn't proceed with even `gqlprune` after installing.
Throwing error `sh: 1: gqlPrune: not found` on running `npx gqlprune init`

**Comment by binary64** [comment]
thank you! this works well (v1.2.2)
